Port to Python 3 - fix int block
int block did not execute, with

Traceback (most recent call last):
  File "/usr/share/sugar/activities/TurtleBlocks.activity/TurtleArt/taprimitive.py", line 1120, in fill
    if error is not None:
UnboundLocalError: local variable 'error' referenced before assignment

Caused by local variable occlusion during exception handler.  Use
another local variable to save the exception.

Similar to 2488c27fd998298bcaa5b82253b64f7d0c73191c.