Fix traceback on turtle reskin
Traceback (most recent call last):
  File "/usr/share/sugar/activities/TurtleBlocks.activity/TurtleArt/talogo.py", line 627, in doevalstep
    self.step.next()
  File "/usr/share/sugar/activities/TurtleBlocks.activity/TurtleArt/talogo.py", line 596, in _evalsym
    result = self.cfun.fcn(self, *self.arglist)
  File "/usr/share/sugar/activities/TurtleBlocks.activity/TurtleArt/taprimitive.py", line 320, in __call__
    return_value = new_prim.func(*new_args, **new_kwargs)
  File "/usr/share/sugar/activities/TurtleBlocks.activity/TurtleArt/talogo.py", line 1152, in reskin
    self.tw.turtles.get_active_turtle().set_shapes([pixbuf])
  File "/usr/share/sugar/activities/TurtleBlocks.activity/TurtleArt/taturtle.py", line 330, in set_shapes
    Gdk.cairo_set_source_pixbuf(
NameError: global name 'Gdk' is not defined

Missing import.