Fix traceback in extras plugin
Traceback (most recent call last):
  File "/usr/share/sugar/activities/TurtleBlocks.activity/TurtleArt/talogo.py", line 627, in doevalstep
    self.step.next()
  File "/usr/share/sugar/activities/TurtleBlocks.activity/TurtleArt/talogo.py", line 596, in _evalsym
    result = self.cfun.fcn(self, *self.arglist)
  File "/usr/share/sugar/activities/TurtleBlocks.activity/TurtleArt/taprimitive.py", line 320, in __call__
    return_value = new_prim.func(*new_args, **new_kwargs)
  File "/usr/share/sugar/activities/TurtleBlocks.activity/plugins/turtle_blocks_extras/turtle_blocks_extras.py", line 1345, in _prim_hideblocks
    self.tw.activity.stop_turtle_button.set_icon("hideshowoff")
AttributeError: 'ToolButton' object has no attribute 'set_icon'

Also caused buttons to not update because handler took early exit.