Port to Python 3 - fix identity block
Identity block did execute with;

Traceback (most recent call last):
  File "TurtleArt/taprimitive.py", line 216, in fill_slots
    if error is None:
UnboundLocalError: local variable 'error' referenced before assignment

Caused by local variable occlusion during exception handler.  Use
another local variable to save the exception.