Port to Python 3 - fix loop blocks
Using repeat block did fail with;

Traceback (most recent call last):
  File "/usr/share/sugar/activities/TurtleBlocks.activity/TurtleArt/talogo.py", line 627, in doevalstep
    next(self.step)
  File "/usr/share/sugar/activities/TurtleBlocks.activity/TurtleArt/talogo.py", line 779, in prim_loop
    raise TypeError("a loop controller must be either an iterator "
TypeError: a loop controller must be either an iterator or a callable that returns an iterator

Caused by iterator special method next renamed to __next__ by Python 3.