Fix query keyboard AttributeError
When a query keyboard block structure is run, nothing appears to be
wrong, but the log contains;

Traceback (most recent call last):
  File "/usr/share/sugar/activities/TurtleBlocks.activity/TurtleArt/tawindow.py", line 3511, in _keypress_cb
    self._key_press(alt_mask, keyname, keyunicode)
  File "/usr/share/sugar/activities/TurtleBlocks.activity/TurtleArt/tawindow.py", line 3574, in _key_press
    self._process_keyboard_commands(keyname, block_flag=True)
  File "/usr/share/sugar/activities/TurtleBlocks.activity/TurtleArt/tawindow.py", line 3643, in _process_keyboard_commands
    self.vbox.set_size_request(Gdk.Screen.width(),
AttributeError: 'TurtleArtWindow' object has no attribute 'vbox'

Use the correct object path.

Introduced by 2781942 ("Address issues with fullscreen").